1. Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.

In [1]:
import numpy as np

A = np.array([[1,2],
             [3,4]])

B = np.array([[5,6],
             [7,8]])


In [ ]:
C = np.vstack((A,B))
print(C)
D = np.hstack((A,B))
print(D)

2. Find common elements between A and B. [Hint : Intersection of two sets]

In [3]:
E = np.array([[1,2],
            [3,4]])

F = np.array([[5,6],   
            [3,7]])

G = np.intersect1d(E,F)

In [4]:
print(G)

[3]


3. Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]

In [8]:
A = np.array([[1,2],
              [3,6]])
condition = np.where((A>5)&(A<10))
print(A[condition])

[6]


4. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0
	url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
	iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [16]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')


In [19]:
numeric_column = iris[:, 1].astype('float')  # sepalwidth
grouping_column = iris[:, 4]  # species

In [28]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
print(iris_2d[(iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)])
print (iris_2d[np.where((iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0))])

[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]
[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


1. From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).

In [30]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [34]:
print(df.iloc[::20,:][['Manufacturer','Model','Type']])

   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


2. Replace missing values in Min.Price and Max.Price columns with their respective mean.

In [36]:
fill = lambda x:x.fillna(x.mean())

In [40]:
df_filled = df[['Min.Price','Max.Price']]=df[['Min.Price','Max.Price']].apply(fill)

In [41]:
df_filled.head()

Min.Price  Max.Price
0  12.900000  18.800000
1  29.200000  38.700000
2  25.900000  32.300000
3  17.118605  44.600000
4  17.118605  21.459091

3. How to get the rows of a dataframe with row sum > 100?

In [65]:
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
df

0   1   2   3
0   15  36  30  34
1   28  12  37  31
2   20  26  33  38
3   33  35  30  17
4   30  36  25  19
5   10  16  36  12
6   26  36  25  21
7   22  18  30  16
8   15  31  25  13
9   34  22  20  28
10  29  38  34  34
11  27  32  33  16
12  26  23  14  28
13  30  27  14  20
14  13  34  13  17

In [66]:
df['rowsums']=df.apply(np.sum, axis=1)
df

0   1   2   3  rowsums
0   15  36  30  34      115
1   28  12  37  31      108
2   20  26  33  38      117
3   33  35  30  17      115
4   30  36  25  19      110
5   10  16  36  12       74
6   26  36  25  21      108
7   22  18  30  16       86
8   15  31  25  13       84
9   34  22  20  28      104
10  29  38  34  34      135
11  27  32  33  16      108
12  26  23  14  28       91
13  30  27  14  20       91
14  13  34  13  17       77

In [ ]:
rowsums = df.apply(np.sum, axis=1)

In [67]:
df[df.rowsums>100]

0   1   2   3  rowsums
0   15  36  30  34      115
1   28  12  37  31      108
2   20  26  33  38      117
3   33  35  30  17      115
4   30  36  25  19      110
6   26  36  25  21      108
9   34  22  20  28      104
10  29  38  34  34      135
11  27  32  33  16      108

In [47]:
output = df.iloc[np.where(rowsums>100)[0][-2:],:]
output

0   1   2   3
13  35  33  32  22
14  15  30  35  33